layout_spectrum: 0.7857375
typography_spectrum: 0.07221712
color:
  saturation: 0.7782643
  lightness: 0.8582983
  brandStrength: 0.773623
  rhythmicContrast: 0.5961593
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
name: mydeas
