layout_spectrum: 0.4269603
typography_spectrum: 0.07221712
color:
  saturation: 0.7782643
  lightness: 0.8582983
  brandStrength: 0.773623
  brandColors:
    - '#060606'
    - '#F3F3F3'
    - '#ACACAC'
    - '#353535'
    - '#5C5C5C'
  rhythmicContrast: 0.5961593
name: mydeas
